# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0.xci
# IP: The module: 'Top_xadc_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xadc_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xadc_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0.xci
# IP: The module: 'Top_xadc_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xadc_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xadc_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
