# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xbar_3/Top_xbar_3.xci
# IP: The module: 'Top_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xbar_3/Top_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xbar_3/Top_xbar_3.xci
# IP: The module: 'Top_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/billy/Projects/FPGA-A100T-2/project/project.srcs/sources_1/bd/Top/ip/Top_xbar_3/Top_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
